FROM alpine:3.13
LABEL author="Vitalii Vrublevskyi"

RUN apk add --no-cache --upgrade bash

RUN mkdir netcat

COPY client.sh /
RUN cp client.sh /netcat/client.sh

WORKDIR /netcat
RUN chmod u+x client.sh

CMD ["/netcat/client.sh"]