FROM alpine:3.13
LABEL author="Vitalii Vrublevskyi"

RUN apk add --no-cache --upgrade bash

RUN mkdir netcat

COPY server.sh /
RUN cp /server.sh /netcat/server.sh

WORKDIR /netcat
RUN chmod u+x server.sh

CMD ["/netcat/server.sh"]
# CMD ["/bin/sh"]