FROM alpine:3.13
LABEL author="Vitalii Vrublevskyi"

RUN apk add --no-cache --upgrade bash

RUN mkdir client
WORKDIR /netcat

COPY client.sh /netcat/client.sh
RUN chmod u+x client.sh

# ENTRYPOINT ["/netcat/", "client.sh"]
CMD ./client.sh